#
#inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - Gemfile

Metrics/LineLength:
  Max: 100

FrozenStringLiteralComment:
  Enabled: false

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

# StructInheritance:
#   Enabled: false

# Metrics/BlockLength:
#   Enabled: true
#   Exclude:
#     - lib/tasks/**/*

# TrailingCommaInLiteral:
#   Enabled: false

# StringLiterals:
#   Enabled: false


# AlignParameters:
#   Enabled: false

# Style/Lambda:
#   Enabled: false

# Style/SignalException:
#   Enabled: false

# Style/NumericLiteralPrefix:
#   Enabled: false

# Style/NumericLiterals:
#   Enabled: false


# Style/ClassAndModuleChildren:
#   Enabled: false

# Lint/SafeNavigationChain:
#   Enabled: false

# Style/SafeNavigation:
#   Enabled: false


# Style/PercentLiteralDelimiters:
#   Description: "Use `%`-literal delimiters consistently"
#   Enabled: true
#   PreferredDelimiters:
#     "%i": "()"
#     "%r": "{}"
#     "%w": "()"
#     "%W": "()"
#     "%x": "[]"
