meta_product_name: "Ca Plan Pour Moi"
meta_title: "Ça Plan Pour Moi - easy planning"
meta_description: "L'intelligence artificielle qui optimise vos planning. Chefs d'équipes, entrez vos besoins. Laissez votre équipe entrer ses disponibilités et laissez nous faire le reste!"
meta_image: "logocppm.jpg"                       # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
